name: DotNet CI Workflow

# Definindo os eventos que acionam o workflow
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # Executa a cada hora

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Action pré-existente do GitHub para checar o código
      - name: Check out code
        uses: actions/checkout@v3

      # Configurar o .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' 

      # Restaurar dependências do .NET
      - name: Restore dependencies
        run: dotnet restore

      # Compilar o projeto
      - name: Build
        run: dotnet build --configuration Release --no-restore

      # Log customizado para o evento de push
      - name: Log push event
        run: echo "Push event detected on branch 'main' at $(date)" >> push_log.txt

      # Verificar log de push
      - name: Display push log
        run: cat push_log.txt

  # Job separado para execução agendada
  scheduled-task:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Log customizado para a ação agendada
      - name: Log scheduled task
        run: echo "Scheduled task executed at $(date)" >> scheduled_task_log.txt

      # Verificar log da tarefa agendada
      - name: Display scheduled task log
        run: cat scheduled_task_log.txt
